### ISSUE TITLE
odoo-server.conf

### ISSUE THREAD

**Issue by printxinc** [lukebranch/odoo-install-scripts#6]
@lukebranch 

Do you have a copy of this anywhere I can get ahold of? I overwrote the one that was created!

**Comment by cliffkujala** [comment]
@billiem

You should be able to recreate the odoo-server.conf file quite easily. Just duplicate the original install script, edit it so that it only included your callouts at the top, and the few sections dealing with the conf file, then make the new .sh file executable. Remove the old/bad conf file using: sudo rm /etc/odoo-server.conf
Run your new .sh for just the creation of the conf.

**Comment by printxinc** [comment]
@cliffkujala

Brilliant... many thanks for such a simple yet great idea!
